version: "3.8"
services:
  frontend:
    image: dietitian-frontend
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_REACT_APP_BACKEND_URL=http://localhost:3005
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: dietitian-backend
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "3005:3005"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb/dietitian
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
